apply plugin: 'com.android.application'

// Sender credentials come from email.properties (git-ignored), never from source.
def emailProps = new Properties()
def emailPropsFile = rootProject.file('email.properties')
if (emailPropsFile.exists()) {
    emailPropsFile.withInputStream { emailProps.load(it) }
}

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.elgindy.sendemailbyjavaemailapi"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "SENDER_EMAIL", "\"${emailProps.getProperty('SENDER_EMAIL', '')}\""
        buildConfigField "String", "SENDER_APP_PASSWORD", "\"${emailProps.getProperty('SENDER_APP_PASSWORD', '')}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'


    implementation files('libs/activation.jar')
    implementation files('libs/additionnal.jar')
    implementation files('libs/mail.jar')
}
